### ISSUE TITLE
GitHub 是你这样用的吗？快删掉这个仓库吧

### ISSUE THREAD

**Issue by shawn-bluce** [Ma-Tao007/ssm_studentMessageManager#1]
开源社区不开源自己的代码，反而给微信公众号引流    背离了开源精神吧

**Comment by Ma-Tao007** [comment]
> 开源社区不开源自己的代码，营养给微信公众号引流背离了开源精神吧

很高心看到你的回复   相信如果你是在查询仓库的时候发现我的，那么你应该已经回复了绝大多数的issues，如果你平时都是为了回复像我这样的仓库内容的话，我代表大众由衷的感谢你！并对你表示由衷的歉意   辛苦你的issues来提醒我们广大的hubers    对于公众号的关注与否   完全取决于阅读者本身   你只是在你的角度上客观的评价这个事情    但是也是非常感谢你的评价！
